export const challengeInQ1 = [
  {
    id: 1,
    day: 1,
    name: "airBnB clone",
    content: "airBnB clone with calendar and map, inspired by PapaRact",
    image: "/portfolio_img/airbnb.png",
    technology: "#NextJS, #tailwindCSS, #mapbox",
    link: "https://airbnb-petherem.vercel.app/",
  },
  {
    id: 2,
    day: 2,
    name: "FX rate calculator",
    content: "FX rate calculator inspired by Traversy Media",
    image: "/portfolio_img/FXrate.png",
    technology: "#JS, #api",
    link: "https://petherem.github.io/fxcalculator/",
  },
  {
    id: 3,
    day: 3,
    name: "Hangman Game",
    content: "Simple Hangman game to master VanillaJS",
    image: "/portfolio_img/Hangman44.png",
    technology: "#JS, #SVG",
    link: "https://petherem.github.io/hangman/",
  },
  {
    id: 4,
    day: 4,
    name: "Football players bible",
    content: "Admin dashboard inspired by LamaDev",
    image: "/portfolio_img/PlayerBible.png",
    technology: "#NextJS #tailwindCSS #api",
    link: "https://playerbible.vercel.app/",
  },
  {
    id: 5,
    day: 5,
    name: "Mockups - Paysafe with WU",
    content: "Mockups for new payment method addition",
    image: "/portfolio_img/PaysafeMockups.png",
    technology: "#NextJS #tailwindCSS #Chartjs",
    link: "https://wupaysafe.vercel.app/",
  },
  {
    id: 6,
    day: 6,
    name: "ChartJS use with NextJS",
    content: "Business case logic with ChartJS in NextJS",
    image: "/portfolio_img/PaysafeBiz.png",
    technology: "#NextJS #tailwindCSS #Chartjs",
    link: "https://wupaysafe.vercel.app/business",
  },
  {
    id: 7,
    day: 7,
    name: "Pizza order with NextJS",
    content: "Pizza ordering website + PayPal",
    image: "/portfolio_img/pizzunia.png",
    technology: "#NextJS #tailwindCSS #MongoDB #PayPal api",
    link: "https://pizzunia.vercel.app/",
  },
  {
    id: 8,
    day: 8,
    name: "Medium Clone with NextJS",
    content: "Blog app with comments, inspired by PapaReact",
    image: "/portfolio_img/medium.png",
    technology: "#NextJS #tailwindCSS #Sanity",
    link: "https://blogers.vercel.app/",
  },
  {
    id: 9,
    day: 9,
    name: "Pizza order 2nd approach",
    content: "Another pizza order website to master NextJS + tailwindCSS",
    image: "/portfolio_img/pizzunia2.png",
    technology: "#NextJS #tailwindCSS #MongoDB",
    link: "https://pizzawarsaw.vercel.app/",
  },
  {
    id: 10,
    day: 10,
    name: "New Admin dashboard",
    content: "Modern Admin dashboard, recreated based on LamaDev tutorial.",
    image: "/portfolio_img/admin44.png",
    technology: "#ReactJS #Sass #Recharts",
    link: "https://new-admin-snowy.vercel.app/",
  },
  {
    id: 11,
    day: 11,
    name: "Expense Tracker",
    content: "Simple expense tracker to master VanillaJS",
    image: "/portfolio_img/ExpenseTracker.png",
    technology: "#VanillaJS",
    link: "https://petherem.github.io/expense_track/",
  },
  {
    id: 12,
    day: 12,
    name: "Landing Page",
    content:
      "Tailwind training portfolio website with NextJS (TraversyMedia inspired)",
    image: "/portfolio_img/manageapp.png",
    technology: "#NextJS, #tailwindCSS",
    link: "https://tailwindtraining.vercel.app/",
  },
  {
    id: 13,
    day: 13,
    name: "Event Website",
    content: "Cycling trip event with Mapbox and tailwindCSS",
    image: "/portfolio_img/balaton.png",
    technology: "#Mapbox, #NextJS, #tailwindCSS",
    link: "https://balaton.vercel.app/",
  },
  {
    id: 14,
    day: 14,
    name: "Professor Portfolio",
    content: "Academic researcher portfolio - template based",
    image: "/portfolio_img/mama.png",
    technology: "#NextJS, #VanillaJS",
    link: "https://www.alinamaciejewska.pl",
  },
  {
    id: 15,
    day: 15,
    name: "Blog",
    content: "Blog website on Sanity, built with NextJS",
    image: "/portfolio_img/bloggy.png",
    technology: "#NextJS, #TailwindCSS #TypeScript #api",
    link: "https://bloggy-ecru.vercel.app/",
  },
  {
    id: 16,
    day: 16,
    name: "Map dashboard",
    content: "WU mapping with Mapbox API - work related project.",
    image: "/portfolio_img/mappy.png",
    technology: "#Mapbox #NextJS, #TailwindCSS",
    link: "https://mapboxwu.vercel.app/",
  },
  {
    id: 17,
    day: 17,
    name: "Youtube clone",
    content: "Quick project to improve NextJS skills along with TailwindCSS.",
    image: "/portfolio_img/pmtube.png",
    technology: "#NextJS #TailwindCSS, #api",
    link: "https://pmtube.vercel.app/",
  },

  {
    id: 18,
    day: 18,
    name: "Tailwind mastering project",
    content: "Part of Brad Traversy course on Udemy.",
    image: "/portfolio_img/fylo.png",
    technology: "#NextJS #TailwindCSS",
    link: "https://colorpicker-ochre.vercel.app/",
  },
  {
    id: 19,
    day: 19,
    name: "Food & cuisine project",
    content: "API and search with NextJS, TailwindCSS",
    image: "/portfolio_img/fudtruck.png",
    technology: "#api, #NextJS #TailwindCSS",
    link: "https://fudtruck.vercel.app/",
  },
  {
    id: 20,
    day: 20,
    name: "Booking.com clone",
    content: "Part one of booking.com clone to deepen NextJS and TailwindCSS experience",
    image: "/portfolio_img/buking.png",
    technology: "#NextJS #TailwindCSS, #api",
    link: "https://bukingapp.vercel.app/",
  },
  {
    id: 21,
    day: 21,
    name: "eCommerce on Sanity ",
    content: "eCommerce website built with Sanity and NextJS. Learning path from JSMastery",
    image: "/portfolio_img/nextcommerce.png",
    technology: "#Sanity #NextJS",
    link: "https://nextcommerce-one-mu.vercel.app",
  },
  {
    id: 22,
    day: 22,
    name: "LoopStudio landing page",
    content: "Project from Brad Traversy TailwindCSS course on Udemy",
    image: "/portfolio_img/loopstudio.png",
    technology: "#TailwindCSS #NextJS",
    link: "https://nextcommerce-one-mu.vercel.app",
  },
  {
    id: 23,
    day: 23,
    name: "Cycling blog",
    content: "Blog on Sanity, NextJS with TailwindCSS",
    image: "/portfolio_img/cyclingwarsaw.png",
    technology: "#TailwindCSS #NextJS #Sanity",
    link: "https://cyclingwarsaw.vercel.app/",
  },
  {
    id: 24,
    day: 24,
    name: "URL shortener - frontend",
    content: "Project from Brad Traversy TailwindCSS course on Udemy",
    image: "/portfolio_img/urlshort.png",
    technology: "#TailwindCSS #NextJS",
    link: "https://shortenerpm.vercel.app/",
  },
  {
    id: 25,
    day: 25,
    name: "QR Code generator",
    content: "Project from Brad Traversy website",
    image: "/portfolio_img/qrcode.png",
    technology: "#TailwindCSS #VanillaJS #qrcode",
    link: "https://qrcoder-three.vercel.app/",
  },
];
