export const projectsShort = [
  {
    id: 1,
    name: "Heliumverse",
    content: "All-in WebApp over Helium concept",
    image: "/portfolio_img/helium.png",
    technology: "#NextJS, #api #MongoDB #styled components #mapbox",
    link: "https://heliumverse.eu",
  },
  {
    id: 2,
    name: "New Admin dashboard",
    content: "Modern Admin dashboard, recreated based on LamaDev tutorial.",
    image: "/portfolio_img/admin44.png",
    technology: "#ReactJS #Sass #Recharts",
    link: "https://new-admin-snowy.vercel.app/",
  },
  {
    id: 21,
    name: "eCommerce on Sanity ",
    content: "eCommerce website built with Sanity and NextJS. Learning path from JSMastery",
    image: "/portfolio_img/nextcommerce.png",
    technology: "#Sanity #NextJS",
    link: "https://nextcommerce-one-mu.vercel.app",
  },
  {
    id: 3,
    name: "Financial Advisory",
    content: "Project - Business website for Financial Advisory office",
    image: "/portfolio_img/joanna4.jpg",
    technology: "#Bootstrap4 #JS #HTML/CSS #api",
    link: "http://www.jfinanse.pl",
  },
  {
    id: 4,
    name: "Crypto currencies market",
    content: "Crypto coins listing - Coin Gecko API connected",
    image: "/portfolio_img/coingecko.png",
    technology: "#React #JS #Bootstrap4 #api",
    link: "https://pmcoins.netlify.app/",
  },
  {
    id: 5,
    name: "Biking blog",
    content: "Biking blog of few good friends loving cyclism.",
    image: "/portfolio_img/RR.jpg",
    technology: "#Bootstrap4, #JS, #HTML/CSS",
    link: "http://rowerowyraj.eu",
  },
  {
    id: 6,
    name: "Western Union Clone",
    content: "WU Austria - digital remittance service clone",
    image: "/portfolio_img/wuclone.png",
    technology: "#ReacJS, #JS, #api",
    link: "https://wuaustria.netlify.app",
  },
  {
    id: 7,
    name: "K&H App with WU",
    content: "Bank app with Money Transfers",
    image: "/portfolio_img/K_H.png",
    technology: "#NextJS, #styled components",
    link: "https://knh-seven.vercel.app/",
  },
  {
    id: 8,
    name: "VOD service",
    content: "IMDB api feed",
    image: "/portfolio_img/vodservice.png",
    technology: "#NextJS, #api #tailwindCSS",
    link: "https://vodservice.vercel.app/",
  },
  {
    id: 10,
    name: "Travel Agency",
    content: "Landing page layout with movie background.",
    image: "/portfolio_img/travelagency.png",
    technology: "#JS, #HTML/CSS",
    link: "https://pmtravel.netlify.app/",
  },
 
  {
    id: 12,
    name: "Event Website",
    content: "Cycling trip event with Mapbox and tailwindCSS",
    image: "/portfolio_img/balaton.png",
    technology: "#Mapbox, #NextJS, #tailwindCSS",
    link: "https://balaton.vercel.app/",
  },
  {
    id: 13,
    name: "Professor Portfolio",
    content: "Academic researcher portfolio - template based",
    image: "/portfolio_img/mama.png",
    technology: "#NextJS, #VanillaJS",
    link: "https://www.alinamaciejewska.pl",
  },
  {
    id: 14,
    name: "Landing Page",
    content:
      "Tailwind training portfolio website with NextJS (TraversyMedia inspired)",
    image: "/portfolio_img/manageapp.png",
    technology: "#NextJS, #tailwindCSS",
    link: "https://tailwindtraining.vercel.app/",
  },
  {
    id: 15,
    name: "Mockups - Paysafe with WU",
    content: "Mockups for new payment method addition",
    image: "/portfolio_img/PaysafeMockups.png",
    technology: "#NextJS #tailwindCSS #Chartjs",
    link: "https://wupaysafe.vercel.app/",
  },
  {
    id: 16,
    name: "My Blog",
    content: "Blog website on Sanity, built with NextJS",
    image: "/portfolio_img/bloggy.png",
    technology: "#NextJS, #TailwindCSS #TypeScript #api",
    link: "https://bloggy-ecru.vercel.app/",
  },
  {
    id: 17,
    name: "Map dashboard",
    content: "WU mapping with Mapbox API",
    image: "/portfolio_img/mappy.png",
    technology: "#Mapbox #NextJS, #TailwindCSS",
    link: "https://mapboxwu.vercel.app/",
  },
  {
    id: 18,
    name: "Food & cuisine project",
    content: "API and search with NextJS, TailwindCSS",
    image: "/portfolio_img/fudtruck.png",
    technology: "#api, #NextJS #TailwindCSS",
    link: "https://fudtruck.vercel.app/",
  },
  {
    id: 19,
    name: "Booking.com clone",
    content: "Part one of booking.com clone to deepen NextJS and TailwindCSS experience.",
    image: "/portfolio_img/buking.png",
    technology: "#NextJS #TailwindCSS, #api",
    link: "https://bukingapp.vercel.app/",
  }
];
